// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: notebooks.proto

package notebooks

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// NotebooksServiceClient is the client API for NotebooksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotebooksServiceClient interface {
}

type notebooksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotebooksServiceClient(cc grpc.ClientConnInterface) NotebooksServiceClient {
	return &notebooksServiceClient{cc}
}

// NotebooksServiceServer is the server API for NotebooksService service.
// All implementations must embed UnimplementedNotebooksServiceServer
// for forward compatibility
type NotebooksServiceServer interface {
	mustEmbedUnimplementedNotebooksServiceServer()
}

// UnimplementedNotebooksServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotebooksServiceServer struct {
}

func (UnimplementedNotebooksServiceServer) mustEmbedUnimplementedNotebooksServiceServer() {}

// UnsafeNotebooksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotebooksServiceServer will
// result in compilation errors.
type UnsafeNotebooksServiceServer interface {
	mustEmbedUnimplementedNotebooksServiceServer()
}

func RegisterNotebooksServiceServer(s grpc.ServiceRegistrar, srv NotebooksServiceServer) {
	s.RegisterService(&NotebooksService_ServiceDesc, srv)
}

// NotebooksService_ServiceDesc is the grpc.ServiceDesc for NotebooksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotebooksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notebooks.NotebooksService",
	HandlerType: (*NotebooksServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "notebooks.proto",
}
